import React, { useMemo } from 'react';
import { Share2 } from 'lucide-react';
import { CalculationSettings, CustodyBlock } from '../types';
import { getOrdinalSuffix } from '../utils/dateUtils';

interface ResultsAreaProps {
  results: { date: Date; occurrence: number }[];
  custodyResults?: CustodyBlock[];
  settings: CalculationSettings;
}


const ResultsArea: React.FC<ResultsAreaProps> = ({ results, custodyResults, settings }) => {
  // DIAGNOSTIC LOGGING
  console.log("[RESULTS] ResultsArea render", {
    mode: settings.mode,
    custodyResultsLength: custodyResults?.length || 0,
    patternResultsLength: results?.length || 0,
    custodyResults: custodyResults
  });

  if (settings.mode === 'custody') {
    console.log("[RESULTS] Custody mode detected");
    if (!custodyResults || custodyResults.length === 0) {
      console.warn("[RESULTS] No custody results to display");
      return null;
    }
    console.log("[RESULTS] Rendering custody results", custodyResults.length);

    const handleDownloadICS = () => {
      let icsContent =
        `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//SaturdayTracker//Custody Schedule//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
`;
      custodyResults.forEach((block) => {
        const startDateStr = block.startDate.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
        // End date for ALL DAY events in ICS is exclusive (start of next day). 
        // Our block.endDate is inclusive. So add 1 day for ICS.
        const icsEndDate = new Date(block.endDate);
        icsEndDate.setDate(icsEndDate.getDate() + 1);
        const endDateStr = icsEndDate.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
        const nowStr = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

        icsContent +=
          `BEGIN:VEVENT
UID:${startDateStr}-${block.owner}@saturdaytracker.com
DTSTAMP:${nowStr}
DTSTART;VALUE=DATE:${startDateStr.substring(0, 8)}
DTEND;VALUE=DATE:${endDateStr.substring(0, 8)}
SUMMARY:Parenting Time - ${block.owner === 'me' ? 'ME' : 'OTHER'}
DESCRIPTION:Generated by saturdaytracker.com (a HOLBANK product). Informational only; follow your court order.
STATUS:CONFIRMED
END:VEVENT
`;
      });

      icsContent += 'END:VCALENDAR';

      const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'custody_schedule.ics');
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    };

    return (
      <div className="bg-white dark:bg-white/5 rounded-xl shadow-lg border border-gray-100 dark:border-white/10 p-6 sm:p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6 border-b border-gray-100 dark:border-white/10 pb-4">
          <div>
            <h3 className="text-lg font-bold text-slate-800 dark:text-white flex items-center gap-2">
              📅 Generated Schedule
            </h3>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              {custodyResults.length} blocks generated.
            </p>
          </div>
          <button
            onClick={handleDownloadICS}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-semibold py-2 px-4 rounded transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download ICS
          </button>
        </div>

        <div className="space-y-3">
          {custodyResults.slice(0, 10).map((block, idx) => (
            <div key={idx} className={`flex justify-between items-center p-3 rounded border-l-4 ${block.owner === 'me'
              ? 'bg-indigo-50 dark:bg-indigo-900/20 border-indigo-500'
              : 'bg-slate-50 dark:bg-slate-800/50 border-slate-400'
              }`}>
              <div className="flex flex-col">
                <span className={`text-xs font-bold uppercase tracking-wider ${block.owner === 'me' ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-500 dark:text-slate-400'
                  }`}>
                  {block.label}
                </span>
                <span className="text-sm font-medium text-slate-800 dark:text-slate-200">
                  {block.startDate.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} – {block.endDate.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                </span>
              </div>
              <div className="text-xs text-slate-400 font-mono">
                {Math.round((block.endDate.getTime() - block.startDate.getTime()) / (1000 * 60 * 60 * 24)) + 1} Days
              </div>
            </div>
          ))}
          {custodyResults.length > 10 && (
            <div className="text-center text-xs text-slate-400 pt-2 italic">
              ...and {custodyResults.length - 10} more blocks (download to see all)
            </div>
          )}
        </div>
      </div>
    );
  }

  // --- STANDARD PATTERN MODE ---
  // UX: Hide everything if no results (Safety check included)
  if (!results || results.length === 0) {
    return null;
  }

  // Logic: Dynamic Header Year Range
  const headerYearRange = useMemo(() => {
    const startYear = results[0].date.getFullYear();
    const endYear = results[results.length - 1].date.getFullYear();
    return startYear === endYear ? `${startYear}` : `${startYear}-${endYear}`;
  }, [results]);

  const alertFiveSaturdays = useMemo(() => {
    const monthsWithFive: string[] = [];
    const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

    // Check next 12 months for 5th saturday alerts
    if (results.length > 0) {
      const checkYear = results[0].date.getFullYear();
      for (let m = 0; m < 12; m++) {
        let count = 0;
        let date = new Date(checkYear, m, 1);
        while (date.getMonth() === m) {
          if (date.getDay() === 6) count++;
          date.setDate(date.getDate() + 1);
        }
        if (count === 5) monthsWithFive.push(`${months[m]} ${checkYear}`);
      }
    }
    return monthsWithFive;
  }, [results]);

  // Logic: Actions - Download CSV
  const downloadCSV = () => {
    const headers = "Date,Day,Pattern,Occurrence\n";
    const rows = results.map(r =>
      `${r.date.toLocaleDateString()},Saturday,${settings.pattern},${r.occurrence}`
    ).join("\n");

    const blob = new Blob([headers + rows], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `schedule-${settings.pattern}.csv`;
    a.click();
  };

  // Logic: Actions - Add to Calendar (ICS)
  const downloadICS = () => {
    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//PatternGen//EN\n";

    results.forEach(item => {
      const start = item.date.toISOString().replace(/-|:|\.\d\d\d/g, "").slice(0, 8); // YYYYMMDD
      icsContent += `BEGIN:VEVENT\nSUMMARY:${settings.pattern} Reminder\nDTSTART;VALUE=DATE:${start}\nDTEND;VALUE=DATE:${start}\nDESCRIPTION:Generated by Universal Pattern Generator\nEND:VEVENT\n`;
    });

    icsContent += "END:VCALENDAR";
    const blob = new Blob([icsContent], { type: 'text/calendar' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `schedule-${settings.pattern}.ics`;
    a.click();
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 animate-slide-up">
      {/* Scrollable Data List */}
      <div className="bg-white dark:bg-white/5 rounded border border-gray-100 dark:border-white/10 overflow-hidden flex flex-col h-[400px] transition-colors duration-300">
        <div className="px-6 py-4 border-b border-gray-100 dark:border-white/10 bg-gray-50 dark:bg-white/5 flex justify-between items-center">
          <h3 className="font-bold text-slate-800 dark:text-slate-100">
            Upcoming Schedule ({headerYearRange})
          </h3>
          <span className="text-xs bg-emerald-500/10 text-emerald-500 dark:bg-emerald-500/20 dark:text-emerald-400 px-2 py-1 rounded-full font-bold">
            {results.length} Occurrences
          </span>
        </div>

        <div className="flex-grow overflow-y-auto px-6 py-2 custom-scrollbar">
          <div className="space-y-1">
            {results.map((item, idx) => (
              <div
                key={`${settings.pattern}-${settings.durationYears}-${idx}`}
                className={`flex items-center justify-between py-3 ${idx !== results.length - 1 ? 'border-b border-gray-50 dark:border-white/5' : ''} hover:bg-gray-50 dark:hover:bg-white/5 transition-colors rounded px-2 group animate-slide-up`}
                style={{ animationDelay: `${idx * 0.03}s` }}
              >
                <div className="flex items-center space-x-4">
                  <div className="bg-gray-100 dark:bg-white/10 p-2 rounded group-hover:bg-emerald-500/10 group-hover:text-emerald-500 dark:group-hover:text-emerald-400 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <div>
                    <p className="font-semibold text-slate-900 dark:text-slate-100">
                      {item.date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </p>
                    <p className="text-xs text-gray-500 dark:text-gray-400 font-medium">Saturday</p>
                  </div>
                </div>
                <div className="text-sm font-bold text-emerald-500 dark:text-emerald-400 bg-emerald-500/10 dark:bg-emerald-500/20 px-3 py-1 rounded-full">
                  ({getOrdinalSuffix(item.occurrence)})
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Actions Block */}
      <div className="flex flex-col space-y-4">
        <div className="bg-white dark:bg-white/5 rounded border border-gray-100 dark:border-white/10 p-6 flex-grow transition-colors duration-300">
          <h3 className="font-bold text-slate-800 dark:text-slate-100 mb-6">Actions</h3>

          <div className="space-y-4">
            {/* 1. SHARE Button - PRIMARY (Emerald) */}
            <button
              onClick={() => {
                if (navigator.share) {
                  navigator.share({
                    title: 'SaturdayTracker',
                    text: 'Check if today is a 2nd or 4th Saturday!',
                    url: window.location.href,
                  }).catch(console.error);
                } else {
                  navigator.clipboard.writeText(window.location.href);
                  alert('Link copied to clipboard!');
                }
              }}
              className="w-full bg-emerald-500 hover:bg-emerald-600 text-white font-bold py-4 px-6 rounded transition-all flex items-center justify-center space-x-3 shadow-lg shadow-emerald-500/20 active:scale-95 border-2 border-transparent hover:border-emerald-500"
            >
              <Share2 className="h-6 w-6 text-white" />
              <span>Share Pattern/Schedule</span>
            </button>

            {/* 2. CALENDAR Buttons - SECONDARY (Slate) */}
            <button
              onClick={downloadICS}
              className="w-full bg-slate-100 dark:bg-white/10 text-slate-700 dark:text-slate-200 font-bold py-4 px-6 rounded hover:bg-slate-200 dark:hover:bg-white/20 transition-all flex items-center justify-center space-x-3 active:scale-95 border-2 border-transparent hover:border-emerald-500"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
              <span>Add to Google Calendar / Outlook</span>
            </button>

            {/* 3. DOWNLOAD Button - SECONDARY (Slate) */}
            <button
              onClick={downloadCSV}
              className="w-full bg-slate-100 dark:bg-white/10 text-slate-700 dark:text-slate-200 font-bold py-4 px-6 rounded hover:bg-slate-200 dark:hover:bg-white/20 transition-all flex items-center justify-center space-x-3 active:scale-95 border-2 border-transparent hover:border-emerald-500"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              <span>Download CSV / PDF</span>
            </button>
          </div>

          <div className="mt-8 bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-900/30 rounded p-4 flex items-start space-x-3">
            <div className="bg-amber-100 dark:bg-amber-900/40 p-1.5 rounded-full text-amber-600 dark:text-amber-400 mt-0.5">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <p className="text-sm text-amber-800 dark:text-amber-200 font-medium">
              Alert: {alertFiveSaturdays[0] || 'A month'} contains a 5th Saturday. Check your specific schedule rules.
            </p>
          </div>
        </div>
      </div>

      {/* Animation Styles */}
      <style>{`
        @keyframes slideUp {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-slide-up {
          animation: slideUp 0.3s ease-out forwards;
        }
      `}</style>
    </div>
  );
};

export default ResultsArea;