import React from 'react';
import SEOPageLayout from '../../layouts/SEOPageLayout';
import { Link } from 'react-router-dom';

const USHolidayConflicts = () => {
    return (
        <SEOPageLayout
            title="Holiday Conflicts and Makeup Time (Overview)"
            h1="Holiday Conflicts & Makeup Time"
            description="What happens when a holiday falls on your parenting weekend?"
        >
            <div className="space-y-8">
                <section>
                    <div className="bg-rose-50 dark:bg-rose-900/10 p-4 rounded-md border-l-4 border-rose-400 mb-6">
                        <p className="text-sm text-rose-800 dark:text-rose-200">
                            <strong>Disclaimer:</strong> This is a general overview. Always check your specific court decree.
                        </p>
                    </div>

                    <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">The "Holiday Trumps Weekend" Rule</h2>
                    <p className="mb-4">
                        In most standard possession orders (like standard state parenting plans), <strong>Holiday schedules take priority over regular weekend schedules.</strong>
                    </p>
                    <p className="mb-4">
                        <strong>Example:</strong> It is "Parent A's" regular 3rd weekend. However, this weekend coincides with Father's Day, and the decree says "Father shall have possession on Father's Day." If "Parent A" is the mother, she loses this weekend. The specific holiday rule wins.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">Does a "Lost" Weekend Get Made Up?</h2>
                    <p className="mb-4">
                        This is a common source of conflict.
                    </p>
                    <p className="mb-4">
                        <strong>Generally: No.</strong> In many standard plans, if a holiday "knocks out" your regular weekend, you do not automatically get a "makeup" weekend later. The calendar just continues rolling.
                    </p>
                    <p className="mb-4">
                        <strong>Exceptions:</strong> Some custom decrees include specific "makeup time" clauses. You must read your order to see if such a clause exists.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">Checking for Conflicts</h2>
                    <p className="mb-4">
                        When using the SaturdayTracker calculator, we currently show the <strong>regular weekend rotation</strong>. We do not yet overlay federal holidays automatically.
                    </p>
                    <p>
                        We recommend comparing the "My Weekend" list generated by our tool against a standard holiday calendar to spot these conflicts early.
                    </p>
                </section>
            </div>
        </SEOPageLayout>
    );
};

export default USHolidayConflicts;
